// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_demo_AlertDemo from "./routes/(demo)/AlertDemo.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_readCsv from "./routes/api/readCsv.ts";
import * as $api_readPosts from "./routes/api/readPosts.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $read_csv_file from "./routes/read_csv_file.tsx";
import * as $read_file from "./routes/read_file.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $_DemoWrapper from "./islands/_DemoWrapper.tsx";
import * as $_WrapperSelect from "./islands/_WrapperSelect.tsx";
import * as $chart from "./islands/chart.tsx";
import * as $demo_AlertDemo from "./islands/demo/AlertDemo.tsx";
import * as $demo_Barchart_index from "./islands/demo/Barchart/index.tsx";
import * as $demo_ReadFile from "./islands/demo/ReadFile.tsx";
import * as $demo_WrapperAlert from "./islands/demo/_WrapperAlert.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(demo)/AlertDemo.tsx": $_demo_AlertDemo,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/readCsv.ts": $api_readCsv,
    "./routes/api/readPosts.ts": $api_readPosts,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/read_csv_file.tsx": $read_csv_file,
    "./routes/read_file.tsx": $read_file,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/_DemoWrapper.tsx": $_DemoWrapper,
    "./islands/_WrapperSelect.tsx": $_WrapperSelect,
    "./islands/chart.tsx": $chart,
    "./islands/demo/AlertDemo.tsx": $demo_AlertDemo,
    "./islands/demo/Barchart/index.tsx": $demo_Barchart_index,
    "./islands/demo/ReadFile.tsx": $demo_ReadFile,
    "./islands/demo/_WrapperAlert.tsx": $demo_WrapperAlert,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
